version: "3.6"
services:
# Define incoming services.
  core_i:
    build: ./navcoin
    image: kosherbacon/docker-navtech:core
    networks:
      - incoming

  subchain_i:
    build: ./subchain
    image: kosherbacon/docker-navtech:subchain
    networks:
      - incoming

  navtech_i:
    build: ./navtech
    image: kosherbacon/docker-navtech:navtech
    depends_on:
      - core_i
      - subchain_i
    networks:
      - incoming
      - navtech

# Define outgoing services.
  core_o:
    build: ./navcoin
    image: kosherbacon/docker-navtech:core
    networks:
      - outgoing

  subchain_o:
    build: ./subchain
    image: kosherbacon/docker-navtech:subchain
    networks:
      - outgoing

  navtech_o:
    build: ./navtech
    image: kosherbacon/docker-navtech:navtech
    depends_on:
      - core_o
      - subchain_o
    networks:
      - navtech
      - outgoing

networks:
  incoming:
  navtech:
  outgoing:
