version: "2"
services:
# Define incoming services.
  core_i:
    build: ./navcoin
    ports:
      - "44444:44444"
    mac_address: 02:00:00:00:00:01
    networks:
      - primary

  subchain_i:
    build: ./subchain
    ports:
      - "33333:33333"
    mac_address: 02:00:00:00:00:02
    networks:
      - primary

  navtech_i:
    build: ./navtech
    ports:
      - "3000:3000"
    mac_address: 02:00:00:00:00:03
    networks:
      - primary

# Define outgoing services.
  core_o:
    build: ./navcoin
    ports:
      - "44444:44444"
    mac_address: 02:00:00:00:01:01
    networks:
      - primary

  subchain_o:
    build: ./subchain
    ports:
      - "33333:33333"
    mac_address: 02:00:00:00:01:02
    networks:
      - primary

  navtech_o:
    build: ./navtech
    ports:
      - "3000:3000"
    mac_address: 02:00:00:00:01:03
    networks:
      - primary

networks:
  primary:
    driver: macvlan
    driver_opts:
      parent: ens160
    ipam:
      driver: default
      config:
        - subnet: 192.168.86.0/24
